- name: Install and start the nginx
  hosts: web
  user: ansible
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present      # present / absent

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        enabled: true