- name: variables check
  hosts: web
  user: ansible

  vars:
    ITEM: Playbook
    AUTHOR: Murali
    TEST: Variables

  tasks:
    - name: without variables
      ansible.builtin.debug:
        msg: "Hello All,
              This is the test play-book
              for the variables"

    - name: with variables
      ansible.builtin.debug:
        msg: "Hello All,
              this is the test {{ITEM}},
              for the {{TEST}} and writer by {{AUTHOR}}"
