- name: variables from variablesfile
  hosts: web
  user: ansible

  vars_files:
  - /home/murali/git_repos/DevOps_Practise/ansible/variables_file

  tasks:
    - name: test variablesfile
      ansible.builtin.debug:
        msg: |
          This is sample {{ITEM}}
          and {{NAME}} made for Testing the {{AUTHOR}}
          Thank You,
          {{AUTHOR}}

