- name: Creating Redis microservice
  hosts: redis
  user: ansible
  become: true

  tasks:
    - name: Install Redis6
      ansible.builtin.dnf:
        name: redis6
        state: installed

    - name: Start and Enable Redis6
      ansible.builtin.service:
        name: redis6
        state: started
        enabled: true

    - name: Allowing Redis6 access from internet
      ansible.builtin.replace:
        path: /etc/redis6/redis6.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start and Enable Redis6
      ansible.builtin.service:
        name: redis6
        state: restarted
      tags:
        - restart