- name: Creating Shipping microservice
  hosts: shipping
  user: ansible
  become: yes

  tasks:
    - name: Install Maven
      ansible.builtin.dnf:
        name: maven
        state: started

    - name: Checking User "roboshop"
      ansible.builtin.command: id roboshop
      register: id_state
      ignore_errors: yes

    - name: Print user "roboshop" state
      ansible.builtin.debug:
        msg: "User roboshop is {{ id_state }}"  

    - name: Creating "roboshop" User
      ansible.builtin.user:
        name: roboshop
      when: id_state.rc !=0

    - name: Checking "app" Directoty state
      ansible.builtin.stat:
        path: /app
      register: app_dir

    - name: Print "app" directory state
      ansible.builtin.debug:
        msg: /app directory is {{ app_dir }}

    - name: Creating "app" directory
      ansible.builtin.file:
        dest: /app
        state: directory
      when: app_dir.stat.exists == False

    - name: Downloading shipping.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp/shipping.zip

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Install maven dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: Renaming jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: Copying "shipping.service" File
      ansible.builtin.copy:
        src: config_files/shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Daemon-reload
      ansible.builtin.systemd:
        name: shipping.service
        state: reloaded

    - name: Start and Enable "shipping.service"
      ansible.builtin.service:
        name: shipping.service
        state: started
        enabled: yes

    - name: install MariaDB-connetor
      ansible.builtin.dnf:
        name: mariadb105-server
        state: started

    - name: Load Schema
      ansible.builtin.command: mysql -h mariadb.vrpproducts.online -uroot -pP@ssw0rd < /app/schema/shipping.sql 

    - name: Start and Enable "shipping.service"
      ansible.builtin.service:
        name: shipping.service
        state: restarted
      tags:
        - restart