- name: Insatll nginx and host the webserver
  hosts: web-tier
  user: ansible
  become: true
  
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Remove default nginx files
      ansible.builtin.file:
        path: /usr/share/ngnix/html
        state: absent

    - name: Download the frontend content
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/web.zip

    - name: Extract the frontend content
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/ngnix/html/
        remote_src: yes

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: config_files/roboshop.conf
        dest: /etc/ngnix/default.d/   

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: true
