---
- name: Installing MongoDB
  hosts: localhost
  become: yes

  vars:
    hosted_zone_id: "Z0733341RBXDY8DMJGHB"
    record_name: "mongodb.vrpproducts.shop"

  tasks:
    - name: Setup the MongoDB repo file
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongo.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc

    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: installed

    - name: Start & Enable MongoDB Service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Enable remote connections to MongoDB
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '^(\s*)bindIp:\s*.*'
        replace: '\1bindIp: 0.0.0.0'

    - name: Restart MongoDB
      ansible.builtin.service:
        name: mongod
        state: restarted
    
    - name: Updating Route53 records
      ansible.builtin.shell: |
        TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
          -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

        PRIVATE_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
          http://169.254.169.254/latest/meta-data/local-ipv4)

        aws route53 change-resource-record-sets \
          --hosted-zone-id {{ hosted_zone_id }} \
          --change-batch "{
            \"Changes\": [{
              \"Action\": \"UPSERT\",
              \"ResourceRecordSet\": {
                \"Name\": \"{{ record_name }}\",
                \"Type\": \"A\",
                \"TTL\": 60,
                \"ResourceRecords\": [{ \"Value\": \"${PRIVATE_IP}\" }]
              }
            }]
          }"

        echo "Updated Private IP Address '${PRIVATE_IP}' for {{ record_name }}"
      register: route53_update_output

    - debug:
        var: route53_update_output.stdout
