---
name: RedisInstall redis components
hosts: localhost
become: yes

vars:
    hosted_zone_id: "Z0733341RBXDY8DMJGHB"
    record_name: "redis6.vrpproducts.shop"

tasks:
  - name: installing redis6
    ansible.builtin.dnf:
      name: redis6
      state: installed

  - name: able remote connections to redis6
    ansible.builtin.replace:
      path: /etc/redis6/redis6.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Start & Enable Redis Service
    ansible.builtin.service:
      name: redis6
      state: started
      enabled: true

  - name: Updating Route53 records
    ansible.builtin.shell: |
      PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv)
      
      aws route53 change-resource-record-sets \
        --hosted-zone-id {{ hosted_zone_id }} \
        --change-batch "{
          \"Changes\": [{
            \"Action\": \"UPSERT\",
            \"ResourceRecordSet\": {
              \"Name\": \"{{ record_name }}\",
              \"Type\": \"A\",
              \"TTL\": 0,
              \"ResourceRecords\": [{ \"Value\": \"${PRIVATE_IP}\" }]
            }
          }]
        }"

      echo "Updated Public IP Address '${PRIVATE_IP}' for {{ record_name }}"
    register: route53_update_output

  - debug:
      var: route53_update_output.stdout