---
- name: Install user components
  hosts: localhost
  become: yes

  vars:
    hosted_zone_id: "Z0733341RBXDY8DMJGHB"
    record_name: "user.vrpproducts.shop"

  tasks:
    - name: Setup the NPM repo
      ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: check roboshop user exist or not
      ansible.builtin.command: id roboshop
      register: out       # output is variable name
      ignore_errors: true

    - when: out.rc != 0
      name: create user roboshop
      become: yes         # we need sudo access for this task
      ansible.builtin.user:
        name: roboshop

    - name: check /app directory exists or not
      ansible.builtin.stat:
        path: /app
      register: directory # directory is variable

    - name: print the directory stats
      ansible.builtin.debug:
        msg: "output: {{ directory }}"
    
    - when: directory.stat.exists == False
      name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download user artifact
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp/user.zip
    
    - name: extract user artifac
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
    
    - name: Installing NPM and dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: Setup user service
      ansible.builtin.copy:
        dest: /etc/systemd/system/user.service
        content: |
          [Unit]
          Description = User Service
          [Service]
          User=roboshop
          Environment=MONGO=true
          Environment=REDIS_HOST=redis.vrpproducts.shop
          Environment=MONGO_URL="mongodb://mongodb.vrpproducts.shop:27017/users"
          ExecStart=/bin/node /app/server.js
          SyslogIdentifier=user

          [Install]
          WantedBy=multi-user.target

    - name: Daemon reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and Enable user service
      ansible.builtin.service:
        name: user
        state: started
        enabled: true

    - name: Setup MongoDB repo
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongo.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc

    - name: Installing MongoDB
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: installed

    - name: Load Schema
      ansible.builtin.shell: | 
        mongosh --host mongodb.vrpproducts.shop < /app/schema/user.js
      register: load_schema_result
      ignore_errors: yes

    - name: Retry schema load on OpenSSL issue
      when: load_schema_result.failed
      ansible.builtin.shell: |
        dnf remove mongodb-mongosh -y
        dnf install mongodb-mongosh-shared-openssl3 -y
        dnf install mongodb-mongosh -y
        mongosh --host mongodb.vrpproducts.shop < /app/schema/user.js
        echo "Schema loaded successfully after retry."

    - name: restarting user Service
      ansible.builtin.service:
        name: user
        state: restarted

    - name: Update Route53 record
      ansible.builtin.shell: |
        TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
          -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

        PRIVATE_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
          http://169.254.169.254/latest/meta-data/local-ipv4)

        aws route53 change-resource-record-sets \
          --hosted-zone-id {{ hosted_zone_id }} \
          --change-batch "{
            \"Changes\": [{
              \"Action\": \"UPSERT\",
              \"ResourceRecordSet\": {
                \"Name\": \"{{ record_name }}\",
                \"Type\": \"A\",
                \"TTL\": 60,
                \"ResourceRecords\": [{ \"Value\": \"${PRIVATE_IP}\" }]
              }
            }]
          }"

        echo "Updated Private IP Address '${PRIVATE_IP}' for {{ record_name }}"
      register: route53_update_output

    - debug:
        var: route53_update_output.stdout