---
- name: Install rabbitmq components
  hosts: localhost
  become: yes

  vars:
    hosted_zone_id: "Z0733341RBXDY8DMJGHB"
    record_name: "rabbitmq.vrpproducts.shop"

  tasks:
    - name: Configure YUM Repos
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/rabbitmq.repo
        content: |
          ## Zero dependency Erlang RPM
          [modern-erlang]
          name=modern-erlang-el9
          # Use a set of mirrors maintained by the RabbitMQ core team.
          # The mirrors have significantly higher bandwidth quotas.
          baseurl=https://yum1.rabbitmq.com/erlang/el/9/$basearch
                  https://yum2.rabbitmq.com/erlang/el/9/$basearch
          repo_gpgcheck=1
          enabled=1
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          [modern-erlang-noarch]
          name=modern-erlang-el9-noarch
          # Use a set of mirrors maintained by the RabbitMQ core team.
          # The mirrors have significantly higher bandwidth quotas.
          baseurl=https://yum1.rabbitmq.com/erlang/el/9/noarch
                  https://yum2.rabbitmq.com/erlang/el/9/noarch
          repo_gpgcheck=1
          enabled=1
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
                https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          ## RabbitMQ Server
          [rabbitmq-el9]
          name=rabbitmq-el9
          baseurl=https://yum2.rabbitmq.com/rabbitmq/el/9/$basearch
                  https://yum1.rabbitmq.com/rabbitmq/el/9/$basearch
          repo_gpgcheck=1
          enabled=1
          # Cloudsmith's repository key and RabbitMQ package signing key
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
                https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          [rabbitmq-el9-noarch]
          name=rabbitmq-el9-noarch
          baseurl=https://yum2.rabbitmq.com/rabbitmq/el/9/noarch
                  https://yum1.rabbitmq.com/rabbitmq/el/9/noarch
          repo_gpgcheck=1
          enabled=1
          # Cloudsmith's repository key and RabbitMQ package signing key
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
                https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md
            
    - name: Clean and Refresh DNF cache
      ansible.builtin.shell: |
        dnf clean all
        dnf makecache

    - name: Update packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        
    - name: install logrotate and rabbitMQ
      ansible.builtin.dnf:
        name: 
          - logrotate
          - erlang
          - rabbitmq-server
        state: installed
        update_cache: yes

    - name: start and enabled RabbitMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted
        enabled: true

    - name: create rabbitmq user and setup permissions
      ansible.builtin.shell: |
        rabbitmqctl add_user roboshop roboshop123
        rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

    - name: Updating Route53 records
      ansible.builtin.shell: |
        TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
          -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

        PRIVATE_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
          http://169.254.169.254/latest/meta-data/local-ipv4)

        aws route53 change-resource-record-sets \
          --hosted-zone-id {{ hosted_zone_id }} \
          --change-batch "{
            \"Changes\": [{
              \"Action\": \"UPSERT\",
              \"ResourceRecordSet\": {
                \"Name\": \"{{ record_name }}\",
                \"Type\": \"A\",
                \"TTL\": 0,
                \"ResourceRecords\": [{ \"Value\": \"${PRIVATE_IP}\" }]
              }
            }]
          }"

        echo "Updated Public IP Address '${PRIVATE_IP}' for {{ record_name }}"
      register: route53_update_output

    - debug:
        var: route53_update_output.stdout
